#!/usr/bin/env bun
// outputty beads-lite — a per-branch task graph. Adopt the beads *model*, not the `bd` tool.
//
// STORAGE IS SPLIT IN TWO, and the split is load-bearing.
//
//   .claude/trails/<branch>.trail.yaml  `tasks:` section  STRUCTURE, hand-authored, NEVER written here
//     └─ id · title · brief · contract · scope · deps · mode · lenses · stage
//   .claude/tasks/<id>.yaml             one file per task  MUTABLE STATE, written by this tool
//     └─ status · spec · tier · attempts (+ the whole record for a discovered task)
//   .claude/tasks.yaml                  DERIVED index, regenerated by `tasks.js index`, never hand-edited
//
// `Bun.YAML.stringify` flattens every `|` block scalar into an escaped one-line string, and every
// mutating command rewrites its whole file. A tool that wrote the trail would therefore destroy the
// hand-authored prose in `core_objective` and in every `decisions` answer. So this tool READS the trail
// and never writes it. One state file per task also means two sessions never write the same file.
//
// `scope` is the FOLDER a task may work in, not a file list — the builder picks the files.
// Layers are DERIVED from deps, never hand-authored. Full reference: skills/outputty/tasks.md.
//
// Runs on bun for `Bun.YAML.parse`/`Bun.YAML.stringify` — node has no builtin YAML support (verified:
// node v26 throws ERR_UNKNOWN_BUILTIN_MODULE on `node:yaml`, and the installed plugin cache ships no
// node_modules).

if (typeof Bun === "undefined") {
  throw new Error(
    'tasks.js requires bun (Bun.YAML) — run it with `bun "${CLAUDE_PLUGIN_ROOT}/skills/outputty/tasks.js" …`',
  );
}

const fs = require("fs");
const path = require("path");
const { execSync } = require("child_process");

// ---------------------------------------------------------------------------
// Pure graph operations (unit-tested in tasks.test.js)
// ---------------------------------------------------------------------------

// Ids of the tasks that are already finished.
function doneIds(tasks) {
  return new Set(tasks.filter((t) => t.status === "done").map((t) => t.id));
}

// Tasks that can be worked right now: open, with every dependency done.
//
// There is deliberately NO same-layer scope check. A layer is built by ONE agent, in sequence, and
// `scope` is a folder rather than a file list, so the check would force every task sharing a folder into
// its own layer. Restore it only if task-level parallelism ever comes back.
function ready(tasks) {
  const done = doneIds(tasks);
  return tasks.filter((t) => t.status === "open" && specSettled(t) && t.deps.every((dep) => done.has(dep)));
}

// The planning lifecycle, and the only thing that decides which stage owns a task.
//
//   drafting ──► settled ──► (build succeeds) ──► done
//      ▲            │
//      │            └──────► (build hits a requirements gap) ──► replan
//      └───────────────────────────────────────────────────────────┘
//                    a replan is an ITERATION, not a fresh start:
//                    it carries `attempts` so the next build knows what died
const SPEC_STATES = ["drafting", "settled", "replan"];

/**
 * Whether a task's spec is settled enough to build.
 *
 * Only `settled` is buildable. `drafting` has never been through planning; `replan` went through and
 * came back. Both belong to the planning stage. Absent means settled, so every graph written before this
 * field keeps scheduling unchanged.
 *
 * @param {object} task - a task record.
 * @returns {boolean} true only when the build stage may pick this task up.
 *
 * `specSettled({ spec: "replan" })` -> false. `specSettled({})` -> true.
 */
function specSettled(task) {
  if (task.spec === undefined) return true;
  if (!SPEC_STATES.includes(task.spec)) {
    throw new Error(`unknown spec state '${task.spec}' on task ${task.id} (states: ${SPEC_STATES.join(", ")})`);
  }
  return task.spec === "settled";
}

/**
 * The tasks the planning stage owns: never specced, or sent back by a build that could not proceed.
 *
 * The build sweep uses `ready`; this is its mirror, and the two are disjoint by construction.
 * @param {object[]} tasks - every task.
 * @returns {object[]} the tasks awaiting a human-in-the-loop pass.
 *
 * `planning([{id:"a",spec:"replan",status:"open"}])` -> that task.
 */
function planning(tasks) {
  return tasks.filter((t) => t.status === "open" && !specSettled(t));
}

// Model tier -> the FULL model id and reasoning effort a dispatch passes after `--`.
//
// Full ids only, never an alias: `opus` resolves to the LATEST model of that family, so it would
// silently select Opus 5 where tier 3 means Opus 4.8. `effort` here is the reasoning-effort knob a
// charter also sets; the task field is `tier`, which selects the model, so the two never collide.
const TIERS = {
  1: { model: "claude-haiku-4-5-20251001", effort: "medium" },
  2: { model: "claude-sonnet-5", effort: "high" },
  3: { model: "claude-opus-4-8", effort: "high" },
  4: { model: "claude-fable-5", effort: "high" },
};

/**
 * The dispatch flags for a task, from its `tier`.
 *
 * Absent tier means 3, which is what build sessions are pinned to today.
 * @param {object} task - a task record.
 * @returns {{model: string, effort: string}} the flags to pass after `--`.
 *
 * `dispatchFlags({ tier: 1 })` -> `{ model: "claude-haiku-4-5-20251001", effort: "medium" }`.
 */
function dispatchFlags(task) {
  const tier = task.tier ?? 3;
  if (!TIERS[tier]) throw new Error(`unknown tier ${tier} on task ${task.id} (tiers: 1, 2, 3, 4)`);
  return TIERS[tier];
}

// The whole plan as ordered layers, in dependency order. Throws on a dependency cycle.
function schedule(tasks) {
  const done = doneIds(tasks);
  let remaining = tasks.filter((t) => t.status !== "done");
  const layers = [];

  while (remaining.length > 0) {
    const layer = remaining.filter((t) => t.deps.every((dep) => done.has(dep)));
    if (layer.length === 0) {
      throw new Error(`cycle or unmet dependency among: ${idList(remaining)}`);
    }

    layers.push(layer);
    layer.forEach((t) => done.add(t.id));
    remaining = remaining.filter((t) => !layer.includes(t));
  }
  return layers;
}

const idList = (tasks) => tasks.map((t) => t.id).join(", ");

// ---------------------------------------------------------------------------
// Storage: the trail holds the structure, one file per task holds the state
// ---------------------------------------------------------------------------

/**
 * The product-memory directory every path below hangs off. `OUTPUTTY_HOME` moves the whole set, which
 * is the seam the tests drive.
 * @returns {string} the `.claude` directory to read and write.
 */
const home = () => process.env.OUTPUTTY_HOME || ".claude";

/** @returns {string} the directory holding the branch trails. */
const trailsDir = () =>
  process.env.OUTPUTTY_TASKS ? path.dirname(process.env.OUTPUTTY_TASKS) : path.join(home(), "trails");

/** @returns {string} the directory holding one mutable-state file per task. */
const stateDir = () => path.join(home(), "tasks");

/** @returns {string} the derived index `tasks.js index` regenerates. */
const indexFile = () => path.join(home(), "tasks.yaml");

/**
 * Resolve the trail for the current branch, and say whether it was named EXPLICITLY.
 *
 * `OUTPUTTY_TASKS` names a trail file directly, so a missing one is a typo, not a fresh branch — it
 * fails loud. The per-branch default is derived, so a missing one just means this branch has no trail
 * yet. A branch name can contain "/" (e.g. "feature/x"); slugified to "-" so the file lands flat beside
 * its siblings rather than at a nested path that never exists.
 *
 * BUILD publishes one branch per LAYER (`feature/x-l1`, `-l2`, …) while the trail is one per FEATURE, so
 * a trailing `-l<N>` layer suffix is stripped before deriving the path. If the stripped path still
 * doesn't exist but a trail named `<slug>-l<N>.trail.yaml` does, that is a near-miss worth failing loud
 * over. The match is anchored to that one pattern, not a bare prefix: a genuinely different feature whose
 * slug happens to prefix another's (`feature-yaml` vs. an existing `feature-yaml-product-memory`) must
 * not be blocked from ever starting its own trail.
 *
 * @returns {{ path: string, explicit: boolean }}
 *
 * `trailFile()` on branch "feature/x-l2" -> `{ path: ".claude/trails/feature-x.trail.yaml", explicit: false }`
 */
function trailFile() {
  if (process.env.OUTPUTTY_TASKS) return { path: process.env.OUTPUTTY_TASKS, explicit: true };
  let branch;
  try {
    branch = execSync("git rev-parse --abbrev-ref HEAD", {
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    }).trim();
  } catch {
    throw new Error("not in a git repo — set OUTPUTTY_TASKS to a trail file, or run inside a branch");
  }
  const slug = branch.replace(/\//g, "-").replace(/-l\d+$/, "");
  const dir = trailsDir();
  const target = `${dir}/${slug}.trail.yaml`;
  if (!fs.existsSync(target) && fs.existsSync(dir)) {
    // Anchored to `<slug>-l<N>.trail.yaml` specifically — see the docstring above for why a bare prefix
    // match is wrong.
    const layerSuffixPrefix = `${slug}-l`;
    const sibling = fs
      .readdirSync(dir)
      .find((f) => f.startsWith(layerSuffixPrefix) && /^\d+\.trail\.yaml$/.test(f.slice(layerSuffixPrefix.length)));
    if (sibling) {
      throw new Error(
        `no trail at ${target}, but a sibling feature trail exists: ${dir}/${sibling} — ` +
          "rename it to the feature-only path if it's the same feature, or set OUTPUTTY_TASKS to override.",
      );
    }
  }
  return { path: target, explicit: false };
}

/**
 * The graph STRUCTURE: the trail's `tasks:` section, exactly as it was hand-authored.
 *
 * @param {string} file - path to a `<branch>.trail.yaml`.
 * @param {boolean} [explicit] - true when the caller named this trail directly (OUTPUTTY_TASKS). A
 *   missing explicit trail fails loud; a missing derived one returns `[]`.
 * @returns {object[]} the structural task records, or `[]` when the trail has no graph yet.
 * @throws when the file is a bare list, or `tasks:` is not a list.
 *
 * `trailTasks(".claude/trails/feature-x.trail.yaml")` -> `[{ id: "t-1", title: "…", deps: [] }]`
 */
function trailTasks(file, explicit = false) {
  if (!fs.existsSync(file)) {
    if (explicit) throw new Error(`trail not found: ${file}`);
    return [];
  }
  const parsed = Bun.YAML.parse(fs.readFileSync(file, "utf8"));
  if (Array.isArray(parsed)) {
    throw new Error(`${file} is a bare list — the graph belongs in the trail's \`tasks:\` section`);
  }
  const tasks = (parsed && parsed.tasks) ?? [];
  if (!Array.isArray(tasks)) throw new Error(`${file}: \`tasks:\` must be a list`);
  return tasks;
}

/**
 * Every task's mutable state, one record per `.claude/tasks/<id>.yaml`.
 *
 * The file name is the id, so a state file can never disagree with the record it holds.
 * @param {string} [dir] - the state directory.
 * @returns {object[]} the state records, in file-name order.
 *
 * `loadState(".claude/tasks")` -> `[{ id: "t-1", status: "done" }]`
 */
function loadState(dir = stateDir()) {
  if (!fs.existsSync(dir)) return [];
  return fs
    .readdirSync(dir)
    .filter((f) => f.endsWith(".yaml") || f.endsWith(".yml"))
    .sort()
    .map((f) => {
      const id = f.replace(/\.ya?ml$/, "");
      const record = Bun.YAML.parse(fs.readFileSync(path.join(dir, f), "utf8")) || {};
      if (record.id && record.id !== id) {
        throw new Error(`${path.join(dir, f)} holds id '${record.id}' — the file name is the id`);
      }
      return { ...record, id };
    });
}

/**
 * The joined graph: the trail's structure, overlaid by each task's state file.
 *
 * A state file with no trail entry is a task discovered mid-build (`tasks.js add`), so it joins the graph
 * on its own. State wins field by field, which is how `amend` widens a scope the trail authored.
 *
 * @param {string} file - path to the trail, as resolved by `trailFile()`.
 * @param {boolean} [explicit] - see `trailTasks`.
 * @param {string} [dir] - the state directory.
 * @returns {object[]} every task, with `status`/`deps`/`scope` defaulted.
 * @throws when two trail records share an `id`.
 *
 * `loadTasks(".claude/trails/feature-x.trail.yaml")` -> `[{ id: "t-1", status: "open", deps: [], … }]`
 */
function loadTasks(file, explicit = false, dir = stateDir()) {
  const structural = trailTasks(file, explicit);
  const seen = new Set();
  for (const t of structural) {
    if (seen.has(t.id)) throw new Error(`duplicate task id: ${t.id}`);
    seen.add(t.id);
  }
  const state = new Map(loadState(dir).map((s) => [s.id, s]));
  const joined = structural.map((t) => withDefaults({ ...t, ...state.get(t.id) }));
  for (const [id, record] of state) if (!seen.has(id)) joined.push(withDefaults(record));
  return joined;
}

const withDefaults = (task) => ({ status: "open", deps: [], scope: [], ...task });

/**
 * Write one task's state file, merging the patch over whatever is already there.
 *
 * This is the ONLY write path for task state, and it touches exactly one file. The trail is never
 * opened for writing.
 *
 * @param {string} dir - the state directory.
 * @param {string} id - the task id, which is also the file name.
 * @param {object} patch - the fields to set.
 * @returns {string} the path written.
 *
 * `saveState(".claude/tasks", "t-1", { status: "done" })` -> `.claude/tasks/t-1.yaml`
 */
function saveState(dir, id, patch) {
  fs.mkdirSync(dir, { recursive: true });
  const target = path.join(dir, `${id}.yaml`);
  const existing = fs.existsSync(target) ? Bun.YAML.parse(fs.readFileSync(target, "utf8")) || {} : {};
  const yaml = Bun.YAML.stringify({ id, ...existing, ...patch }, null, 2);
  fs.writeFileSync(target, yaml.endsWith("\n") ? yaml : yaml + "\n");
  return target;
}

/**
 * One index record per task: the durable, repo-level view `docs.js tasks` reads.
 * @param {object} task - a joined task.
 * @returns {object} `{ id, kind, status, deps, summary, link }`.
 */
const indexRecord = (task) => ({
  id: task.id,
  kind: task.kind ?? "task",
  status: task.status ?? "open",
  deps: task.deps ?? [],
  summary: task.title ?? "",
  link: `${home()}/tasks/${task.id}.yaml`,
});

/**
 * Rebuild `.claude/tasks.yaml` from every trail's `tasks:` section plus every state file.
 *
 * The index spans branches, so it reads the whole trails directory rather than the current branch's
 * trail alone. It is derived output: a hand edit is overwritten on the next run.
 *
 * @param {{trails: string, state: string, out: string}} paths - where to read and write.
 * @returns {object[]} the records written, sorted by id.
 */
function buildIndex({ trails, state, out }) {
  const all = new Map();
  if (fs.existsSync(trails)) {
    for (const f of fs
      .readdirSync(trails)
      .filter((x) => x.endsWith(".trail.yaml"))
      .sort()) {
      for (const task of trailTasks(path.join(trails, f))) {
        all.set(task.id, { ...all.get(task.id), ...task });
      }
    }
  }
  for (const record of loadState(state)) all.set(record.id, { ...all.get(record.id), ...record });

  const records = [...all.values()].sort((a, b) => (a.id < b.id ? -1 : 1)).map(indexRecord);
  const body = records.length ? Bun.YAML.stringify(records, null, 2) : "";
  const header = "# DERIVED — regenerate with `tasks.js index`. Never hand-edit this file.\n";
  fs.mkdirSync(path.dirname(path.resolve(out)), { recursive: true });
  fs.writeFileSync(out, header + (body.endsWith("\n") || !body ? body : body + "\n"));
  return records;
}

// ---------------------------------------------------------------------------
// CLI
// ---------------------------------------------------------------------------

const commands = {
  // ready [--json] — the ids ready to work right now.
  ready(tasks, { json }) {
    const result = ready(tasks);
    console.log(json ? JSON.stringify(result) : idList(result) || "(none ready)");
  },

  // planning [--json] — the tasks the PLANNING stage owns: never specced, or sent back by a build.
  planning(tasks, { json }) {
    const result = planning(tasks);
    console.log(json ? JSON.stringify(result) : idList(result) || "(nothing waiting on planning)");
  },

  // dispatch <id> [--json] — the model flags this task should be started with.
  //
  // The orchestrator pastes these after `--` in `herdr agent start`, so the tier-to-model mapping lives
  // in one place that is read by a command.
  dispatch(tasks, { json, args }) {
    const id = args.positional[0];
    const task = tasks.find((t) => t.id === id);
    if (!task) throw new Error(`no such task: ${id}`);
    const flags = dispatchFlags(task);
    console.log(json ? JSON.stringify(flags) : `--model ${flags.model} --effort ${flags.effort}`);
  },

  // schedule [--json] — the derived layer plan.
  schedule(tasks, { json }) {
    const layers = schedule(tasks);
    if (json) {
      console.log(JSON.stringify(layers));
      return;
    }
    const lines = layers.map((layer, i) => `Layer ${i + 1}: ${idList(layer)}`);
    console.log(lines.join("\n") || "(no open tasks)");
  },

  // add <id> <title> [--deps a,b --scope folder --brief "…" --from parent]
  //
  // Discovered work has no trail entry, so its whole record goes in its own state file.
  add(tasks, { args, state }) {
    const [id, title] = args.positional;
    if (!id) throw new Error("add needs an id");
    if (tasks.some((t) => t.id === id)) throw new Error(`task ${id} already exists`);
    saveState(state, id, {
      title: title || "",
      status: "open",
      deps: commaList(args.deps),
      scope: commaList(args.scope),
      brief: args.brief || "",
      ...(args.from ? { discovered_from: args.from } : {}),
    });
  },

  // amend <id> [--scope x,y --brief '…'] — widen an open task mid-build.
  //
  // QA can find that a done-condition genuinely needs an edit outside its folder. Widening is the whole
  // point: a task that has already been built cannot have its scope narrowed without orphaning committed
  // work, so `done` tasks are refused outright. The widened scope is written to the task's state file;
  // the trail keeps the scope PLAN authored.
  amend(tasks, { args, state }) {
    const id = args.positional[0];
    const task = tasks.find((t) => t.id === id);
    if (!task) throw new Error(`no task ${id}`);
    if (task.status === "done") throw new Error(`task ${id} is done — amend orphans committed work`);
    if (args.scope === undefined && args.brief === undefined) {
      throw new Error("amend needs --scope or --brief");
    }
    const patch = {};
    if (args.scope !== undefined) {
      const added = commaList(args.scope).filter((s) => !task.scope.includes(s));
      if (!added.length) throw new Error(`task ${id} already covers that scope`);
      patch.scope = [...task.scope, ...added];
    }
    if (args.brief !== undefined) patch.brief = args.brief;
    saveState(state, id, patch);
  },

  // close <id> — mark a task done. Writes one state file and never touches the trail.
  close(tasks, { args, state }) {
    const id = args.positional[0];
    const task = tasks.find((t) => t.id === id);
    if (!task) throw new Error(`no task ${id}`);
    saveState(state, id, { status: "done" });
  },

  // index [--json] — regenerate `.claude/tasks.yaml` from every trail plus every state file.
  index(tasks, { json, trails, state, out }) {
    const records = buildIndex({ trails, state, out });
    console.log(json ? JSON.stringify(records) : `${out}: ${records.length} task(s) indexed`);
  },
};

// "a, b," -> ["a", "b"] — trims each item and drops empties.
const commaList = (value) =>
  (value || "")
    .split(",")
    .map((s) => s.trim())
    .filter(Boolean);

// Parse "add foo --deps a,b" into { positional: ["foo"], deps: "a,b" }. A flag with no value
// (next token is another --flag, or absent) is left empty rather than swallowing the next flag.
function parseArgs(argv) {
  const args = { positional: [] };
  for (let i = 0; i < argv.length; i++) {
    if (argv[i].startsWith("--")) {
      const next = argv[i + 1];
      if (next !== undefined && !next.startsWith("--")) {
        args[argv[i].slice(2)] = next;
        i++;
      } else {
        args[argv[i].slice(2)] = "";
      }
    } else {
      args.positional.push(argv[i]);
    }
  }
  return args;
}

function main(argv) {
  const [name, ...rest] = argv;
  const command = commands[name];
  if (!command) {
    console.error(
      "usage: ready | planning | dispatch <id> | schedule | index | " +
        "add <id> <title> [--deps a,b --scope x,y --brief '…' --from p] | " +
        "amend <id> [--scope x,y --brief '…'] | close <id>  [--json]",
    );
    process.exit(1);
  }

  const json = rest.includes("--json");
  const args = parseArgs(rest.filter((a) => a !== "--json"));

  try {
    const { path: trail, explicit } = trailFile();
    const state = stateDir();
    command(loadTasks(trail, explicit, state), {
      args,
      json,
      trail,
      state,
      trails: trailsDir(),
      out: indexFile(),
    });
  } catch (err) {
    console.error(err.message);
    process.exit(1);
  }
}

module.exports = {
  ready,
  planning,
  schedule,
  commands,
  trailFile,
  trailTasks,
  loadTasks,
  loadState,
  saveState,
  buildIndex,
  indexRecord,
  stateDir,
  trailsDir,
  indexFile,
  specSettled,
  dispatchFlags,
  TIERS,
  SPEC_STATES,
};

if (require.main === module) {
  main(process.argv.slice(2));
}
